---
language: java

sudo: false

jdk:
    - oraclejdk8

cache:
    directories:
        - $HOME/.m2
        - $HOME/.sonar/cache


before_script:
    - echo $HOME
    - echo $JAVA_OPTS
    - echo $MAVEN_OPTS


## Submit the code to code coverage
after_success:
    - bash <(curl -s https://codecov.io/bash)


addons:
    # https://docs.travis-ci.com/user/sonarqube/
    sonarqube:
    branches:
      - master
      - maintenance

# the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
