version: "2"
services:
    haproxy:
        image: haproxy:1.7.2-alpine
        hostname: haproxy
        volumes:
            - ./conf/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        ports:
            - 172.17.0.1:80:80
            - 172.17.0.1:999:9999
        networks:
            - development

    keycloak:
        image: jboss/keycloak:2.5.0.Final
        hostname: "keycloack"
        environment:
            - KEYCLOAK_LOGLEVEL=DEBUG
            - KEYCLOAK_USER=manager
            - KEYCLOAK_PASSWORD=admin

        expose:
            - "8080"
            - "9990"
            - "9999"

        networks:
            - development

    wildfly:
        image: fcorreia/wildfly:10.0.0.Final
        hostname: "wildfly"
        environment:
            - DEBUG=true
        expose:
            - "8080"
            - "9990"
            - "9999"
        networks:
            - development

    postgres:
        image: postgres:9.6-alpine
        hostname: postgres
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        volumes:
            - /opt/redcross/postgres:/var/lib/pgsql
        expose:
            - "5432"
        networks:
            - development

networks:
    development:
