version: "2"
services:
    haproxy:
        image: haproxy:1.7.2-alpine
        hostname: haproxy
        volumes:
            - ./conf/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        ports:
            # Bind to docker interface
            # 172.17.0.1	redcross.local
            - 172.17.0.1:80:80
            - 172.17.0.1:443:443
            - 172.17.0.1:9990:9990
        networks:
            - development

    keycloak:
        image: jboss/keycloak:2.5.0.Final
        hostname: "keycloack"
        env_file:
            - keycloak.env
        environment:
            - DEBUG=true
            ## Exporting
            #- JAVA_OPTS="$JAVA_OPTS -Dkeycloak.migration.action=export -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/tmp/keycloack -Dkeycloak.migration.realmName=red-cross"
            ## Importing
            - JAVA_OPTS=-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/keycloack/red-cross.json -Dkeycloak.migration.strategy=IGNORE_EXISTING
        volumes:
            - ./src/keycloack-theme/src/main/resources/theme/redcross:/opt/jboss/keycloak/themes/red-cross:ro
            - ./conf/keycloack/keycloak-redcross.json:/tmp/keycloack/red-cross.json:ro
        expose:
            - "8080"
            - "9990"
            - "9999"

        networks:
            - development

    wildfly:
        image: fcorreia/wildfly:10.1.0.Final
        hostname: "wildfly"
        env_file:
            - wildfly.env
        environment:
            - DEBUG=true
        volumes:
            - ./build/keycloak-wildfly-adapter/modules/system/add-ons/keycloak:/opt/wildfly/modules/system/add-ons/keycloak:ro
            - ./conf/wildfly/keycloak-init.sh:/docker-init.d/00.keycloak-init.sh:ro
            - ./build/keycloak-wildfly-adapter/bin/adapter-install-offline.cli:/tmp/keycloak-adapter-install.cli:ro
            - ./conf/wildfly/init-red-cross.cli:/tmp/redcross-init.cli:ro
        expose:
            - "8080"
            - "9990"
            - "9999"
        networks:
            - development

    postgres:
        image: postgres:9.6-alpine
        hostname: postgres
        env_file:
            - keycloak.env
        volumes:
            - /opt/redcross/postgres:/var/lib/pgsql
        expose:
            - "5432"
        networks:
            - development

networks:
    development:
